In [1]:
import bittensor as bt
s=bt.subtensor("finney")
m=s.metagraph(1)
m

metagraph(netuid:1, n:1024, block:1679858, network:finney)

In [3]:
v=m.validator_permit
v

Parameter containing:
tensor([False, False,  True,  ..., False, False, False])

In [6]:
import torch
vuids = torch.where(v==1)[0]
vuids

tensor([   2,    3,    5,    6,    7,   12,   15,   19,   20,   35,   38,   41,
          48,   53,   54,   61,   64,   77,   80,   84,   95,  116,  117,  125,
         130,  132,  137,  152,  153,  168,  173,  200,  205,  220,  226,  229,
         234,  239,  259,  277,  280,  290,  309,  312,  313,  337,  338,  348,
         356,  380,  386,  393,  418,  444,  448,  450,  457,  463,  468,  476,
         480,  493,  502,  518,  520,  527,  535,  538,  550,  556,  563,  566,
         572,  583,  586,  593,  604,  617,  620,  641,  652,  656,  661,  666,
         673,  674,  687,  689,  703,  714,  717,  720,  725,  733,  737,  738,
         742,  763,  788,  792,  793,  795,  799,  811,  814,  829,  832,  838,
         844,  849,  860,  871,  876,  891,  913,  917,  935,  940,  942,  946,
         964,  970,  983, 1001, 1002, 1004, 1006, 1013])

In [15]:
quids=torch.where(m.S[vuids] > 10000)[0]
quids

tensor([  0,   1,   2,   3,   4,   5,  15,  16,  27,  30,  31,  34,  41,  45,
         51,  62,  63,  72,  81,  85,  86,  90,  94,  98, 103, 115, 119, 120,
        123])

In [17]:
import numpy as np
qaxons = np.asarray(m.axons)[quids]
qaxons

array([AxonInfo( /ipv4/51.91.215.161:11003, 5GMq8QGy633wWbbi7GWDjB5TDouFx3zkm1a516RGd3vniLrN, 5CiQiCy9dZASdizydEJdP6A7hKmBjCKRp28EYSQkehWiRSau, 610 ),
       AxonInfo( /ipv4/216.153.57.106:6688, 5HiwKZsa535Yc1rweY3Qt2v3p9cCzxzjPZJ7trbKjDpcPrDy, 5GsvYsviXvugYLTJ1EsxMporNKujJBnaJvzJT4cnTvpzBwZD, 610 ),
       AxonInfo( /ipv4/34.90.71.181:8091, 5HEo565WAy4Dbq3Sv271SAi7syBSofyfhhwRNjFNSM2gP9M2, 5ChuGqW2cxc5AZJ29z6vyTkTncg75L9ovfp8QN8eB8niSD75, 620 ),
       AxonInfo( /ipv4/64.247.206.79:8091, 5HK5tp6t2S59DywmHRWPBVJeJ86T61KjurYqeooqj8sREpeN, 5E7W9QXNoW7se7B11vWRMKRCSWkkAu9EYotG5Ci2f9cqV8jn, 610 ),
       AxonInfo( /ipv4/51.91.30.166:40203, 5EXYcaCdnvnMZbozeknFWbj6aKXojfBi9jUpJYHea68j4q1a, 5CsxoeDvWsQFZJnDCyzxaNKgA8pBJGUJyE1DThH8xU25qUMg, 601 ),
       AxonInfo( /ipv4/149.137.225.62:8091, 5F4tQyWrhfGVcNhoqeiNsR6KjD4wMZ2kfhLj4oHYuyHbZAc3, 5Ccmf1dJKzGtXX7h17eN72MVMRsFwvYjPVmkXPUaapczECf6, 610 ),
       AxonInfo( /ipv4/146.59.92.165:60019, 5GU9Qqs2Dx6fK5DRnLEYnti1qBM1LFLhBXofR7kE9Wsmb2M2, 5CQ6